# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogFinish.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameEnded(object):
    def setupUi(self, GameEnded):
        GameEnded.setObjectName("GameEnded")
        GameEnded.resize(320, 240)
        GameEnded.setStyleSheet("background-color: rgb(41, 41, 41)")
        self.label = QtWidgets.QLabel(GameEnded)
        self.label.setGeometry(QtCore.QRect(20, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.hiddenWord = QtWidgets.QLabel(GameEnded)
        self.hiddenWord.setGeometry(QtCore.QRect(60, 90, 200, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.hiddenWord.setFont(font)
        self.hiddenWord.setStyleSheet("color: rgb(83,141,78);")
        self.hiddenWord.setAlignment(QtCore.Qt.AlignCenter)
        self.hiddenWord.setObjectName("hiddenWord")
        self.playAgain_Button = QtWidgets.QPushButton(GameEnded)
        self.playAgain_Button.setGeometry(QtCore.QRect(100, 180, 113, 32))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.playAgain_Button.setFont(font)
        self.playAgain_Button.setStyleSheet("color: white;")
        self.playAgain_Button.setObjectName("playAgain_Button")
        self.label_3 = QtWidgets.QLabel(GameEnded)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(GameEnded)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(GameEnded)
        QtCore.QMetaObject.connectSlotsByName(GameEnded)

    def retranslateUi(self, GameEnded):
        _translate = QtCore.QCoreApplication.translate
        GameEnded.setWindowTitle(_translate("GameEnded", "Dialog"))
        self.label.setText(_translate("GameEnded", "Oops... seems like you finished you tries."))
        self.hiddenWord.setText(_translate("GameEnded", "WORD"))
        self.playAgain_Button.setText(_translate("GameEnded", "PLAY AGAIN"))
        self.label_3.setText(_translate("GameEnded", "THE HIDDEN WORD WAS"))
        self.label_4.setText(_translate("GameEnded", "But don\'t worry! You can try again!"))
